In [138]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier,plot_importance
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score

In [139]:
data = pd.read_csv("Dataset.csv").drop("customerID",axis = 1)

In [140]:
data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [141]:
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [142]:
data.tail()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [144]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [145]:
null_vall = data.isnull().sum()
print("Count of Null Values: ",null_vall)

Count of Null Values:  gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [146]:
data["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [147]:
data["TotalCharges"].value_counts()

TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

In [148]:
data.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [149]:
data[data["TotalCharges"] == " "]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [150]:
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"],errors="coerce")

In [151]:
data.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [152]:
data.dropna(inplace=True)

In [153]:
data.shape
data.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [154]:
pd.crosstab(
    data["Contract"],
    data["Churn"],
    normalize="index"
) * 100

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.722826  11.277174
Two year        97.151335   2.848665

In [155]:
data.groupby("Churn")["tenure"].describe()

        count       mean        std  min   25%   50%   75%   max
Churn
No     5163.0  37.650010  24.076940  1.0  15.0  38.0  61.0  72.0
Yes    1869.0  17.979133  19.531123  1.0   2.0  10.0  29.0  72.0

In [156]:
data.groupby("Churn")["MonthlyCharges"].describe()

        count       mean        std    min    25%    50%     75%     max
Churn
No     5163.0  61.307408  31.094557  18.25  25.10  64.45  88.475  118.75
Yes    1869.0  74.441332  24.666053  18.85  56.15  79.65  94.200  118.35

In [157]:
data["Churn"] = data["Churn"].map({
    "No" : 0,
    "Yes" : 1
})

In [158]:
x = data.drop("Churn",axis = 1)
y = data["Churn"]

In [159]:
print("Input Shape: ",x.shape)
print("Output Shape: ",y.shape)

Input Shape:  (7032, 19)
Output Shape:  (7032,)

In [160]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [161]:
print("Training Shape: ",x_train.shape)
print("Training Shape: ",y_train.shape)
print("Testing Shape: ",x_test.shape)
print("Testing Shape: ",y_test.shape)

Training Shape:  (4922, 19)
Training Shape:  (4922,)
Testing Shape:  (2110, 19)
Testing Shape:  (2110,)

In [162]:
num_attributes = [
    "SeniorCitizen",
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]
cat_attributes = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [163]:
num_pipeline = Pipeline([
    ("Num",SimpleImputer(strategy="mean")),
    ("Normalize",StandardScaler())
])

In [164]:
num_pipeline

Pipeline(steps=[('Num', SimpleImputer()), ('Normalize', StandardScaler())])

In [165]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("Encode", OneHotEncoder(handle_unknown="ignore"))
])

In [166]:
cat_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('Encode', OneHotEncoder(handle_unknown='ignore'))])

In [167]:
full_pipeline = ColumnTransformer([
    ("num",num_pipeline,num_attributes),
    ("cat",cat_pipeline,cat_attributes)
])

In [168]:
full_pipeline

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('Num', SimpleImputer()),
                                                 ('Normalize',
                                                  StandardScaler())]),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encode',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [169]:
x_train_prepared = full_pipeline.fit_transform(x_train)
x_test_prepared = full_pipeline.transform(x_test)

In [170]:
print("Training Shape: ",x_train_prepared.shape)
print("Testing Shape: ",x_test_prepared.shape)

Training Shape:  (4922, 45)
Testing Shape:  (2110, 45)

In [171]:
#Train Model
print("\n===== Logistic Regression Results =====\n")
model = LogisticRegression(n_jobs=1,random_state=42,max_iter=1000)
model.fit(x_train_prepared,y_train)
log_pred = model.predict(x_test_prepared)
accu = accuracy_score(y_test,log_pred)

print("Accuracy Score: ",accu * 100)

print("Precision Score: ",precision_score(y_test,log_pred))

print("Recall Score: ",recall_score(y_test,log_pred))

print("F1 Score: ",f1_score(y_test,log_pred))

print("Error: ", 1 - accu)

print(log_pred[0:10])

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, log_pred))

===== Logistic Regression Results =====

Accuracy Score:  79.5260663507109
Precision Score:  0.6375266524520256
Recall Score:  0.5329768270944741
F1 Score:  0.5805825242718446
Error:  0.204739336492891
[0 0 1 0 0 0 0 1 0 0]

Confusion Matrix:
[[1379  170]
 [ 262  299]]

In [172]:
#Random Forest Classifier Model
print("\n===== Random Forest Classifier Results =====\n")
ran_model = RandomForestClassifier(n_estimators=42,random_state=42)
ran_model.fit(x_train_prepared,y_train)
ran_pred = ran_model.predict(x_test_prepared)

print("Accuracy:",
      accuracy_score(y_test, ran_pred))

print("Precision Score: ",precision_score(y_test,ran_pred))

print("Recall Score: ",recall_score(y_test,ran_pred))

print("F1 Score: ",f1_score(y_test,ran_pred ))

print("Error: ", 1 - accu)

print("\nClassification Report:")
print(classification_report(y_test, ran_pred ))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, ran_pred ))


print("\nSample Predictions:")
print(ran_pred [:10])

===== Random Forest Classifier Results =====

Accuracy: 0.7767772511848341
Precision Score:  0.6071428571428571
Recall Score:  0.45454545454545453
F1 Score:  0.5198776758409785
Error:  0.204739336492891

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1549
           1       0.61      0.45      0.52       561

    accuracy                           0.78      2110
   macro avg       0.71      0.67      0.69      2110
weighted avg       0.76      0.78      0.77      2110


Confusion Matrix:
[[1384  165]
 [ 306  255]]

Sample Predictions:
[0 0 1 0 0 0 0 1 0 0]

In [173]:
print("\n===== XGB Classifier Results =====\n")
x_model = XGBClassifier(
    n_estimator=200,
     learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

x_model.fit(x_train_prepared,y_train)
x_pred = x_model.predict(x_test_prepared)

print("Accuracy:",
      accuracy_score(y_test, x_pred))

print("Precision Score: ",precision_score(y_test,x_pred))

print("Recall Score: ",recall_score(y_test,x_pred))

print("F1 Score: ",f1_score(y_test,x_pred ))

print("Error: ", 1 - accu)

print("\nClassification Report:")
print(classification_report(y_test, x_pred ))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,x_pred ))


print("\nSample Predictions:")
print(x_pred [:10])

===== XGB Classifier Results =====

Accuracy: 0.7962085308056872
Precision Score:  0.6465324384787472
Recall Score:  0.5151515151515151
F1 Score:  0.5734126984126984
Error:  0.204739336492891

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1549
           1       0.65      0.52      0.57       561

    accuracy                           0.80      2110
   macro avg       0.74      0.71      0.72      2110
weighted avg       0.79      0.80      0.79      2110


Confusion Matrix:
[[1391  158]
 [ 272  289]]

Sample Predictions:
[0 0 1 0 0 0 0 1 0 0]

D:\Anaconda\Lib\site-packages\xgboost\training.py:200: UserWarning: [21:48:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [174]:
feat_name = full_pipeline.get_feature_names_out()
print("Feature Name: ",feat_name)

Feature Name:  ['num__SeniorCitizen' 'num__tenure' 'num__MonthlyCharges'
 'num__TotalCharges' 'cat__gender_Female' 'cat__gender_Male'
 'cat__Partner_No' 'cat__Partner_Yes' 'cat__Dependents_No'
 'cat__Dependents_Yes' 'cat__PhoneService_No' 'cat__PhoneService_Yes'
 'cat__MultipleLines_No' 'cat__MultipleLines_No phone service'
 'cat__MultipleLines_Yes' 'cat__InternetService_DSL'
 'cat__InternetService_Fiber optic' 'cat__InternetService_No'
 'cat__OnlineSecurity_No' 'cat__OnlineSecurity_No internet service'
 'cat__OnlineSecurity_Yes' 'cat__OnlineBackup_No'
 'cat__OnlineBackup_No internet service' 'cat__OnlineBackup_Yes'
 'cat__DeviceProtection_No' 'cat__DeviceProtection_No internet service'
 'cat__DeviceProtection_Yes' 'cat__TechSupport_No'
 'cat__TechSupport_No internet service' 'cat__TechSupport_Yes'
 'cat__StreamingTV_No' 'cat__StreamingTV_No internet service'
 'cat__StreamingTV_Yes' 'cat__StreamingMovies_No'
 'cat__StreamingMovies_No internet service' 'cat__StreamingMovies_Yes'
 'cat__Contract_Month-to-month' 'cat__Contract_One year'
 'cat__Contract_Two year' 'cat__PaperlessBilling_No'
 'cat__PaperlessBilling_Yes'
 'cat__PaymentMethod_Bank transfer (automatic)'
 'cat__PaymentMethod_Credit card (automatic)'
 'cat__PaymentMethod_Electronic check' 'cat__PaymentMethod_Mailed check']

In [175]:
importance_df = pd.DataFrame({
    "Feature": feat_name,
    "Importance": x_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

importance_df.head(15)

                                Feature  Importance
36         cat__Contract_Month-to-month    0.375177
16     cat__InternetService_Fiber optic    0.100929
27                  cat__TechSupport_No    0.054674
38               cat__Contract_Two year    0.039520
17              cat__InternetService_No    0.036896
18               cat__OnlineSecurity_No    0.027003
15             cat__InternetService_DSL    0.025859
13  cat__MultipleLines_No phone service    0.024708
1                           num__tenure    0.021234
37               cat__Contract_One year    0.016035
35             cat__StreamingMovies_Yes    0.014772
11                cat__PhoneService_Yes    0.014375
32                 cat__StreamingTV_Yes    0.014020
2                   num__MonthlyCharges    0.013115
10                 cat__PhoneService_No    0.012928

In [179]:
from sklearn.pipeline import Pipeline
import joblib

final_model = Pipeline([
    ("preprocessor", full_pipeline),
    ("classifier", model)
])

final_model.fit(x_train, y_train)

joblib.dump(final_model, "churn_pipeline.pkl")

['churn_pipeline.pkl']

In [178]:
import sklearn
print("Training sklearn:", sklearn.__version__)

Training sklearn: 1.7.2